config/routes.rb
SMSDemo::Application.routes.draw do

  resources "messages" do
    collection do 
      get "outbox"
      get "draft"
      get "balance"
      post "add_credit"
      get "credit"
    end
  end

  root :to  => "home#index"

end

app/models/message.rb
class Message
  include Mongoid::Document
  field :from, :type => String
  field :to, :type => String
  field :content, :type => String
  field :message_type, :type => String
  
  def send_sms
    p = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    # Send a text message
    result = p.send_sms(:number => self.to, :message => self.content) if p.connect?
    p.close
    result
  end
  
  def self.inbox
    p = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    messages = (p.connect?) ? p.inbox : nil
    p.close
    messages
  end

  def self.outbox
    p = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    messages = (p.connect?) ? p.outbox : nil
    p.close
    messages
  end

  def self.smsc
    p = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    smsc = (p.connect?) ? p.smsc : nil
    p.close
    smsc
  end

  def self.delete(id)
    p = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    result = (p.connect?) ? p.delete(id) : nil
    p.close
    result
  end

  def self.get_by_id(id)
    p = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    result = (p.connect?) ? p.get(id) : nil
    p.close
    result
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gsm_modem = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.inbox
  end
  
  def new
    @message = Message.new({:from => Message.smsc})
  end
  
  def show
    @new_message = Message.new({:from => Message.smsc})
    @message = Message.get_by_id(params[:id])
  end
  
  def destroy
    if Message.delete(params[:id])
      flash[:notice]='Message was successfully deleted.'
      redirect_to '/messages' and return
    else
      flash[:error]='Message was fail deleted.'
      redirect_to '/messages' and return
    end

  end
  
  def create
    @message = Message.new(params[:message])
    @message.message_type = "Outbox"
    respond_to do |format|
      if @message.save && @message.send_sms
        flash[:notice]='Message was successfully created.'
        format.html { redirect_to "/messages"}
        format.json { head :no_content }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def outbox
    @messages = Message.outbox
  end
  
  def draft
    
  end

  def balance
    @gsm_modem = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    @balance = @gsm_modem.money("*101#")
    @bonus_balance = @gsm_modem.money("*102#")
    @gsm_modem.close
  end

  def add_credit
    @gsm_modem = GSM::Modem.new({:port => "/dev/ttyUSB1", :debug => true})
    @messages = @gsm_modem.add_credit(params[:card_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.erb
<h3>
  <p>Send And Receive SMS Text Messages</p>

  <p> With Ruby And A GSM/GPRS Modem</p>
</h3>
<h3><p>Modem Information</p></h3>
<table class="table">
  <!--<tr>-->
    <!--<td>-->
      <!--Phone Number-->
    <!--</td>-->
    <!--<td>-->

    <!--</td>-->
  <!--</tr>-->
  <tr>
    <td>
      Manufacturer
    </td>
    <td>
      <%= @gsm_modem.manufacturer %>
    </td>
  </tr>
  <tr>
    <td>
      Frequency
    </td>
    <td>
      <%= @gsm_modem.frequency %>
    </td>
  </tr>
  <tr>
    <td>
      Software
    </td>
    <td>
      <%= @gsm_modem.software %>
    </td>
  </tr>
  <tr>
    <td>
      IMEI
    </td>
    <td>
      <%= @gsm_modem.IMEI %>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>SMS Demo</title>
    <%= yield :head %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body class="preview" data-spy="scroll" data-target=".subnav" data-offset="80">
    
    <%= render :partial => "shared/header" %>
    
    <div class="container">
      <% flash.each do |name, msg| %>
        <% if name != :share %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
        <% else %>
          <div class="alert alert-info" >
            <a class="close" data-dismiss="alert">×</a>
            <%= msg %>
            <br /><br />
            <span class='st_facebook_large' displayText='Facebook'></span>
            <span class='st_twitter_large' displayText='Tweet'></span>
            <span class='st_googleplus_large' displayText='Google +'></span>
            <span class='st_tumblr_large' displayText='Tumblr'></span>
            <span class='st_wordpress_large' displayText='WordPress'></span>
            <span class='st_digg_large' displayText='Digg'></span>
            <span class='st_delicious_large' displayText='Delicious'></span>
            <span class='st_blogger_large' displayText='Blogger'></span>
            <span class='st_email_large' displayText='Email'></span>
            <span class='st_sharethis_large' displayText='ShareThis'></span>
          </div>
          <% end %>
      <% end %>

      <div class="row">
        <div class="span12"><%= yield %></div>
      </div>

      <%= render :partial => "shared/footer" %>
    </div>
  </body>
  
</html>

app/views/messages/_form.html.erb
<%
is_edit=(controller.action_name=="edit")
is_new=(controller.action_name=="new")
is_create = (controller.action_name=="create")
is_update = (controller.action_name=="update")
%>
<%= form_for(@message,:html => { :class => "form-horizontal", :multipart => true})  do |f| %>
  <fieldset>
    <% if @message.errors.any? %>
      <div class="alert alert-error error" data-alert="alert" id="error-message">
        <a class="close" data-dismiss="alert">×</a>
        <ul>
          <% @message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <script type="text/javascript">
      function afterLoad(){
        $(".alert-message").alert('close');
      };
    </script>


    <div class="control-group">
      <label class="control-label">From Phone Number</label>
      <div class="controls">
         <%= f.text_field :from, :disabled => "disabled", :class=>"input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">To Phone Number</label>
      <div class="controls">
        <%= f.text_field :to, :class=>"input-xlarge" %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Messages</label>
      <div class="controls">
        <%= f.text_area :content, :class=>"input-xlarge", :rows => 6, :maxlength => 159 %>
        <% if is_new || is_create%>
        <div class="max-character" style="margin-left: 160px;">0/160 characters</div>
        <% end %>
      </div>
    </div>
  <div class="form-actions">
    <%= f.submit 'Submit' , :class=>'btn btn-large btn-primary' %>
  <% end %>

app/views/messages/add_credit.html.erb
<h1>
  <%= @messages %>
</h1>
<%= link_to "Back", credit_messages_path %>

app/views/messages/balance.html.erb
<h3><p>Balance Information</p></h3>
<table class="table">
  <tr>
    <td>
      Main Balance
    </td>
    <td>
      <%= @balance %>
    </td>
  </tr>

  <tr>
    <td>
      Bonus Balance
    </td>
    <td>
      <%= @bonus_balance %>
    </td>
  </tr>
</table>

app/views/messages/credit.html.erb
<form action="/messages/add_credit" method="post">
  <fieldset>
    <div class="control-group">
      <label class="control-label">Card ID</label>

      <div class="controls">
        <input name="card_id" id="card_id" type="text"/>
      </div>
    </div>
    <div class="form-actions">
      <input type="submit" class="btn btn-large btn-primary" value="Submit">
    </div>
  </fieldset>
</form>

app/views/messages/draft.html.erb
<h1>Sms#draft</h1>
<p>Find me in app/views/sms/draft.html.erb</p>

app/views/messages/edit.html.erb
<h1>Editing listing</h1>
<style>
  .navbar{
    display: none;
}
</style>
<%= render 'form' %>

<%= link_to 'Show', @listing,class:'btn btn-large' %> 
<%= link_to 'Back', listings_path,class:'btn btn-large' %>
</div>
</fieldset>

app/views/messages/index.html.erb
<h3>Inbox</h3>
<table class="table">
  <tr>
    <th>
      Message ID
    </th>
    <th>
      Sender
    </th>
    <th>
      Message
    </th>
    <th>
      Date Sent
    </th>
    <th>
      Action
    </th>
  </tr>
  <% if @messages.present? %>
      <% @messages.each do |message| %>
          <tr>
            <td>
              <%= message.id %>
            </td>
            <td>
              <%= message.sender %>
            </td>
            <td>
              <%= message.message %>
            </td>
            <td>
              <%= message.time %>
            </td>
            <td width="200px">
              <%= link_to('Reply', "/messages/#{message.id}", :class =>"btn btn-info") %>
              <%= link_to('Destroy', "/messages/#{message.id}", method: :delete, data: { confirm: 'Are you sure?' },:class =>"btn btn-danger") %>
            </td>
          </tr>
      <% end %>
  <% else %>
      <td colspan="4" style="text-align: center;">Can not connect SMS Modem</td>
  <% end %>
</table>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form' %>
</div>
</fieldset>

app/views/messages/outbox.html.erb
<h3>Outbox</h3>
<table class="table">
  <tr>
    <th>
      Message ID
    </th>
    <th>
      Receiver
    </th>
    <th>
      Message
    </th>
    <th>
      Action
    </th>
  </tr>
  <% if @messages.present? %>
      <% @messages.each do |message| %>
          <tr>
            <td>
              <%= message.id %>
            </td>
            <td>
              <%= message.sender %>
            </td>
            <td>
              <%= message.message %>
            </td>
            <td>
              <%= link_to('Destroy', "/messages/#{message.id}", method: :delete, data: { confirm: 'Are you sure?' },:class =>"btn btn-danger") %>
            </td>
          </tr>
      <% end %>
  <% else %>
      <td colspan="4" style="text-align: center;">Can not connect SMS Modem</td>
  <% end %>
</table>

app/views/messages/show.html.erb
<%
   is_edit=(controller.action_name=="edit")
   is_new=(controller.action_name=="new")
   is_create = (controller.action_name=="create")
   is_update = (controller.action_name=="update")
%>
<%= form_for(@new_message,:html => { :class => "form-horizontal", :multipart => true})  do |f| %>
    <fieldset>
      <% if @new_message.errors.any? %>
          <div class="alert alert-error error" data-alert="alert" id="error-message">
            <a class="close" data-dismiss="alert">×</a>
            <ul>
              <% @new_message.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <script type="text/javascript">
          function afterLoad(){
              $(".alert-message").alert('close');
          };
      </script>


      <div class="control-group">
        <label class="control-label">From Phone Number</label>
        <div class="controls">
          <%= f.text_field :from, :disabled => "disabled", :class=>"input-xlarge" %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">To Phone Number</label>
        <div class="controls">
          <%= f.text_field :to, :class=>"input-xlarge", :value => @message.sender, :readonly => "readonly" %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">Messages</label>
        <div class="controls">
          <%= f.text_area :content, :class=>"input-xlarge", :rows => 6, :maxlength => 159 %>
          <% if is_new || is_create%>
              <div class="max-character" style="margin-left: 160px;">0/160 characters</div>
          <% end %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.submit 'Submit' , :class=>'btn btn-large btn-primary' %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <hr>
  <div class="row-fluid navbar">
    <div class="span6">SMS Demo(Ruby & GSM Modem)</div>
    <div style="float:right; text-align:right;" class="span6">
      Design by
      <a href="http://www.deekau.net" target="_blank">Deekau</a>
      Copyright &copy; <%= Time.now.strftime("%Y") %>
    </div>
  </div>
</footer> 

app/views/shared/_header.html.erb
<!-- Navbar ================================================== -->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/"><%= image_tag "logo.png" %></a>
      <br />
      <ul class ="secondary-nav dropdown"><div class="nav-collapse collapse">

          <ul class="nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "New Message", new_message_path %></li>
            <li><%= link_to "Inbox", messages_path %></li>
            <li><%= link_to "Outbox", outbox_messages_path %></li>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Account Information<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Balance", balance_messages_path %></li>
                <li><%= link_to "Add Credit", credit_messages_path %></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<br />